version: '3'
services:
#mssql docker
  tattoostudio-sql:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=QWElkj132!
      - MSSQL_PID=Developer
    ports:
      - 1401:1433
    networks:
      - tattoostudionet

  tattoostudio-api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings:DefaultConnection=Server=tattoostudio-sql,1433;Database=TattooStudioRSII;User=sa;Password=QWElkj132!;ConnectRetryCount=0
    ports:
      - 80:80
    networks:
      - tattoostudionet      
    links:
      - tattoostudio-sql
    depends_on:
      - tattoostudio-sql
      
networks:
  tattoostudionet:
    driver: bridge 